### PR TITLE
Add mvp documentation.

### PR DESCRIPTION
**Pull request by jpmedley**
@reillyeon If you have a better name for this, let me know. I want to come up with something standard so that eventually (hopefully) people just know what to look for.

### CODE REVIEW

**Comment by jpmedley** [comment]
cc: @inexorabletash

**Comment by reillyeon** [comment]
Can you put it in a "mdn-drafts" folder or something which indicates the purpose and why it has references to MDN?

**Comment by jpmedley** [comment]
@reillyeon PTAL

**Review by reillyeon — APPROVED** [review]

**Comment by jpmedley** [comment]
Would you mind merging this? I don't have the authority to.

**Pull request merged**
